### ISSUE TITLE
催更ing

### ISSUE THREAD

**Issue by Ruvikm** [Aiden-L/Vue2Demo#1]
已经8天没有更新了！！！！！！！！

**Comment by Aiden-L** [comment]
马上就更

**Comment by Aiden-L** [comment]
下个版本将会增加element的支持

**Comment by Aiden-L** [comment]
敬请期待

**Comment by Aiden-L** [comment]
2.0版本已经更新，2.0系列版本为在1.0基础上添加了ui组件，需要轻量化demo（无ui版本）请查看中的[releases](https://github.com/Aiden-L/Vue2Demo/releases)中的1.0版本
